### ISSUE TITLE
Sorry, we are experiencing some network issues causing your request to timeout

### ISSUE THREAD

**Issue by PotatoGan** [zhangrenyang/chatgpt#1]
Sorry, we are experiencing some network issues causing your request to timeout. Please check your network connection and try again later. If the problem persists, it may be due to temporary issues with our server which we will resolve as soon as possible. Thank you for your understanding and patience.

**Comment by zhangrenyang** [comment]
The issue has been resolved. Please uninstall the current version and install the new one.
