### ISSUE TITLE
Clear option should be for individual query

### ISSUE THREAD

**Issue by monis01** [zhangrenyang/chatgpt#10]
**What**

The clearing option  should be for individual query and not jut for entire list
![image](https://github.com/zhangrenyang/chatgpt/assets/7036532/17c21a1a-0593-42b8-9fc4-e493eb4d3539)

e.g. : 
![image](https://github.com/zhangrenyang/chatgpt/assets/7036532/e15e9614-0023-4553-9923-68964f8379e6)

So individual query can be removed

**Comment by zhangrenyang** [comment]
I have already added this feature. Please download the [new version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to experience it.
