### ISSUE TITLE
Request failed with status code 429

### ISSUE THREAD

**Issue by irajeshh** [zhangrenyang/chatgpt#14]
Added the API key I retrived, but still facing the same error.
Also I validated the key, it showed key is valid.

My maximum requests were about to 10 in an hour, but this doesn't work now.

`Your requests are too frequent. Please try again later. If it still doesn't work, please bind your own API key or execute the command ChatGPT: Refresh API key🔄🔑 to obtain the latest API key.`

**Comment by zhangrenyang** [comment]
I have resolved this issue, please download the [new version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to experience it. I hope you enjoy using it.
