### ISSUE TITLE
If you want the plugin to support a new language, you can request it here.

### ISSUE THREAD

**Issue by zhangrenyang** [zhangrenyang/chatgpt#15]
You can check the languages currently supported [here](https://marketplace.visualstudio.com/search?target=VSCode&category=Language%20Packs&sortBy=Installs).

**Comment by Ethan-bit101** [comment]
Please help me my chatgpt extension got an error "Source: Chatgpt (Extension) - Request failed with status code 404"

**Comment by zhangrenyang** [comment]
> Please help me my chatgpt extension got an error "Source: Chatgpt (Extension) - Request failed with status code 404"

please try again

**Comment by lostwark** [comment]
![image](https://github.com/zhangrenyang/chatgpt/assets/141449351/4c03dfc6-6110-472a-8d04-0dbad6c2fa4f)
i try to fix for 2h and nothing repare this error

**Comment by zhangrenyang** [comment]
I have resolved the issue. Please uninstall and then [reinstall ](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to proceed.

**Comment by zhangrenyang** [comment]
> ![image](https://user-images.githubusercontent.com/141449351/261879190-4c03dfc6-6110-472a-8d04-0dbad6c2fa4f.png) i try to fix for 2h and nothing repare this error

I have resolved the issue. Please uninstall and then [reinstall ](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to proceed.

**Comment by zhangrenyang** [comment]
Please download the latest version and try again, ensuring that the model setting is correct, which should be gpt-3.5-turbo.

**Comment by Sward44** [comment]
I created a new key in "https://platform.openai.com/account/api-keys" and inserted it in the VSCode/ChatGPT/Bind your own API key🔀🔑 tool where I pasted the freshly created code.
But then I go to VSCode/ChatGPT/Validate API key✔️🔑 and I still get this message:
"Failure, you've bound your own API key: mSEeaO9ekKo0kDbl****************ougur3wsrAKpCGkJ, its status is invalid and cannot be used. Please log into the official website to check if it has expired or if there is insufficient balance."

**Comment by BRUNO0315** [comment]
**I have the same problem and I can't solve it, any advice?dv**

key🔀🔑 tool where I pasted the freshly created code.
But then I go to VSCode/ChatGPT/Validate API key✔️🔑 and I still get this message:
"Failure, you've bound your own API key: *********************************************************, its status is invalid and cannot be used. Please log into the official website to check if it has expired or if there is insufficient balance."

**Comment by giulioiannelli** [comment]
Another one here having the same issue

`Failure, you've bound your own API key: tG2HzLF8WVGF7hud****************6RflseAirFRTM4M2, its status is invalid and cannot be used. Please log into the official website to check if it has expired or if there is insufficient balance.`

**Comment by danieltorscho** [comment]
Same here

**Comment by camiloabrilth1999** [comment]
I have the same problem, I got several errors and it says that it has to do with the API KEY but I already tried with a direct curl of the api key and it works correctly, I think it is a problem of the extension.

![image](https://github.com/zhangrenyang/chatgpt/assets/22029023/fffeda3a-f444-4852-9ef7-a868862887ad)
![image](https://github.com/zhangrenyang/chatgpt/assets/22029023/34ca41fa-5ef4-4dcc-ac98-5a926ea92c25)

**Comment by Finger03** [comment]
![Captura de tela 2024-10-03 205607](https://github.com/user-attachments/assets/9b179a2b-02e9-47fb-8f3e-98a719a82a21)
how to fix that?
