### ISSUE TITLE
quota of 200 inquiries

### ISSUE THREAD

**Issue by chouaxong** [zhangrenyang/chatgpt#16]
Each user is granted a quota of 200 inquiries, however, you have already exhausted your quota. By linking your own API key, you will be able to make inquiries without any limits.

**Comment by zhangrenyang** [comment]
This software operates for free, and personal financial resources are limited, therefore, a limit of 200 is set for each user. Beyond this limit, please bind your own API key for unlimited use, and you can enable the context conversation function. Thank you for your feedback, and I hope you enjoy using it.

**Comment by chouaxong** [comment]
Thanks for free 200 inquiries. but in my country Not available
OpenAI's services are not available in your country. how to solve this problem?
