### ISSUE TITLE
Action buttons are missing in bottom

### ISSUE THREAD

**Issue by irajeshh** [zhangrenyang/chatgpt#17]
In practical, when a `long code` is generated based on our query, we need to **scroll to the top** inorder to copy it.
But each time scrolling to top and coming down to the bottom is really **time consuming**, I'm facing the same problem in Chat gpt also, and I sent a feedback about the issue. 

If the buttons are placed in both `top` and `bottom` of the results, it wil drastially increase the productivity.

I tried almost all the plugins related to Chat gpt, but none of them having the feature. so requesting here to implement it here.
Incase you feel my point is valid, please add that in next version.

Here's the expected result.
![Untitled-1](https://github.com/zhangrenyang/chatgpt/assets/85046336/f8e6ca3d-6c57-4428-aee3-805987b0652e)

**Comment by zhangrenyang** [comment]
Thank you for your feedback. I have added this feature in the new version. Please [download it](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) and give it a try.

**Comment by irajeshh** [comment]
Wow you've implemented that quick, thank you and using `1.6.58`.

_One small Idea, please give an rating start icon button to link to [this repo](https://github.com/zhangrenyang/chatgpt), so that people can star it as fast as possilbe. This project deserves more stars._
