### ISSUE TITLE
上下文功能无法使用

### ISSUE THREAD

**Issue by dabinn** [zhangrenyang/chatgpt#18]
谢谢作者开发这么好的extension
最近使用的时候发现他对上下文似乎没反应
已经设了API key，然后验证看起来没问题
然而测试上下文时是这样的结果
![image](https://github.com/zhangrenyang/chatgpt/assets/21699064/5cd524cd-5182-41aa-98b0-4534ab452573)

**Comment by zhangrenyang** [comment]
Please download the latest version and try again, ensuring that the model setting is correct, which should be gpt-3.5-turbo.
