### ISSUE TITLE
Question to the extensions

### ISSUE THREAD

**Issue by rirjkl19** [zhangrenyang/chatgpt#2]
First of all thank you for providing this extension to the us developers as it helps a lot, However I have some question that was not answered in the extension description.

1. **Privacy Policy:** Does the extension take our prompts and question or is stored in the author's accounts? (I'm assuming the author have multiple accounts having access to multiple API keys) 
2. **Billing:** It seems to advocate a free ChatGPT use as long as it is not GPT4 which is great. However I'm kinda concerned with the GPT 3.5 variants. Is the history for using this models stored in the authors account? which points me to the my question to 1. Is there a way for me to point this histories and account if I have my own ChatGPT plus subscription?

I hope i get enlighten with this questions. Thank you

**Comment by zhangrenyang** [comment]
1. This extension does not collect users' prompts and questions, nor are they stored in the author's account. All data is stored locally on the user's computer, which means that if the user changes computers, the conversation history will be lost.
2. This plugin supports GPT4, but users need to bind their own API key that supports GPT4. These histories are stored locally on the user's computer and there is no way to point the histories towards a user's account as this history is only stored locally.
3. This extension simply acts as a simple proxy when the official domain network is not available. The proxy server does not have any business logic or processing. Users can also provide their own proxy server.
