### ISSUE TITLE
error 404 on every request

### ISSUE THREAD

**Issue by Sogl** [zhangrenyang/chatgpt#22]
Client request error. Please retry. If it still doesn't work, please bind your own API key or execute the command ChatGPT: Refresh API key🔄🔑 to obtain the latest API key.

Tried to refresh token and reload VSCode much time without luck.

**Comment by zhangrenyang** [comment]
I have resolved the issue. Please uninstall and then [reinstall ](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to proceed.
