### ISSUE TITLE
文本框内粘贴会导致jupyter单元格被复制

### ISSUE THREAD

**Issue by bxrjmfh** [zhangrenyang/chatgpt#26]
经过检查，快捷键没有任何冲突，且内容无法复制到输入框中

**Comment by zhangrenyang** [comment]
> 经过检查，快捷键没有任何冲突，且内容无法复制到输入框中

This is the copy button. Click to copy. May I ask where you need to copy and paste?

![copy](https://github.com/zhangrenyang/chatgpt/assets/3096013/e7f2bc7b-cea6-43bf-964e-d8fa85947d50)

**Comment by zhangrenyang** [comment]
This might be due to formatting issues with Jupyter itself. You can first paste the content into Notepad as plain text, and then copy and paste it into the input field.
