### ISSUE TITLE
No Copy and Paste!? oh dear

### ISSUE THREAD

**Issue by cachatj** [zhangrenyang/chatgpt#28]
For the love of god, is the inability to copy and paste into and out of this thing effecting eveyrone or what?! its maddening....

**Comment by zhangrenyang** [comment]
This is the copy button. Click to copy. May I ask where you need to copy and paste?

![copy](https://github.com/zhangrenyang/chatgpt/assets/3096013/e7f2bc7b-cea6-43bf-964e-d8fa85947d50)
