### ISSUE TITLE
協助翻譯

### ISSUE THREAD

**Issue by a19901201** [zhangrenyang/chatgpt#3]
我想協助翻譯但是我不知道您希望我從哪裡開始進行?

**Comment by zhangrenyang** [comment]
Which language support would you like to see added?

**Comment by a19901201** [comment]
I can assist with translating Traditional Chinese (Taiwan), Traditional Chinese (Hong Kong), and Simplified Chinese. I hope to have Traditional Chinese (Taiwan) available in the program.

**Comment by PetrDebil** [comment]
When I send a message to the chat, the following error appears: "Request failed. The server could not understand or accept the sent request content. Please check your request content, including URL, request method, request headers, and request body. If the issue persists, please contact your service provider." I have no problems with the Internet and I have not found a solution on the Internet, although I may have searched badly. Thank you in advance for the answer

**Comment by zhangrenyang** [comment]
> When I send a message to the chat, the following error appears: "Request failed. The server could not understand or accept the sent request content. Please check your request content, including URL, request method, request headers, and request body. If the issue persists, please contact your service provider." I have no problems with the Internet and I have not found a solution on the Internet, although I may have searched badly. Thank you in advance for the answer

I have resolved this issue, please download the [new version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to experience it. I hope you enjoy using it.

**Comment by zhangrenyang** [comment]
> I can assist with translating Traditional Chinese (Taiwan), Traditional Chinese (Hong Kong), and Simplified Chinese. I hope to have Traditional Chinese (Taiwan) available in the program.

I have resolved this issue, please download the [new version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to experience it. I hope you enjoy using it.

![QQ截图20230730144301](https://github.com/zhangrenyang/chatgpt/assets/3096013/a16335f4-e40c-41ef-bbb2-56441b93e645)
