### ISSUE TITLE
Is there a text document somewhere for managing predefined questions?

### ISSUE THREAD

**Issue by ndunn219** [zhangrenyang/chatgpt#30]
It would be great if there were a text document for managing predefined prompts in JSON. Something like:
```
{
  "title": "Your Title Here", // A short title to select
  "prompt": "Your Prompt Here", // The actual prompt, which might be long
  "append_selected_text": true // A boolean indicating if the selected text in the active document should be appended to the prompt
}
```

**Comment by zhangrenyang** [comment]
Thank you for your suggestion! This feature has been implemented and is now live. Please download the [new version]( https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to try it out, and feel free to provide feedback if you encounter any issues.

> Press `Ctrl+Shift+P (Command + Shift + P)`, type `ChatGPT: Edit Predefined Prompts ✏️`, and hit Enter to open a `prompts.json` file where you can centrally edit predefined prompts.
> After this, you can type `/` in the input box to pop up the predefined selection menu. Use the up and down arrow keys to select a predefined prompt, then press Enter or click to confirm and automatically fill the input box with the prompt.
