### ISSUE TITLE
界面滚动问题

### ISSUE THREAD

**Issue by SuiYunsy** [zhangrenyang/chatgpt#31]
可以做到像官网一样打断滚动吗？输出内容很多的时候一直把视图往下扯，没法打断滚动。
或者可以让用户选择手动滚动吗？

**Comment by zhangrenyang** [comment]
I have implemented this feature. Please download [the latest version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to try it out. 

If the user tries to scroll up during the generation process, the automatic scrolling to the bottom will stop.
