### ISSUE TITLE
使用自己的chatgpt key返回429需要如何解决，重新启动vscode或重新安装了插件也是这样

### ISSUE THREAD

**Issue by hzqgogogo** [zhangrenyang/chatgpt#33]
![image](https://github.com/zhangrenyang/chatgpt/assets/7456835/78b725cd-3f2d-45cc-99ed-c25a3eb89d7f)

**Comment by bruce1408** [comment]
I have also encountered a similar problem.

**Comment by hzqgogogo** [comment]
已收到你的邮件！

**Comment by zhangrenyang** [comment]
This is not a BUG; sometimes the balance of the key is insufficient. In this case, you can bind your own key. I will replenish new key resources when I find out, but this may not always be timely.

**Comment by hzqgogogo** [comment]
已收到你的邮件！
