### ISSUE TITLE
Feature Request: New Chat command

### ISSUE THREAD

**Issue by dukartbr** [zhangrenyang/chatgpt#36]
It'd be helpful to be able to create an entirely new chat rather than append the new question to the last chat. This would help keep the sidebar organized by topics.

**Comment by zhangrenyang** [comment]
![微信截图_20240511143556](https://github.com/zhangrenyang/chatgpt/assets/3096013/76075110-d447-45ea-8eba-e46d599b24f4)

You can click +NewChat to start a brand-new conversation.
