### ISSUE TITLE
增加的预定义提示词 希望能集成到右键菜单

### ISSUE THREAD

**Issue by 370569218** [zhangrenyang/chatgpt#4]
增加的预定义提示词 希望能集成到右键菜单

**Comment by zhangrenyang** [comment]
Thank you for your suggestion. It has been accepted, and the feature is currently under development...

**Comment by zhangrenyang** [comment]
Custom prompts integrated into the right-click menu is now live.
[Install the new version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt)

### Choose Predefined Prompt ➕
Press the shortcut keys `Ctrl+Shift+P (Command + Shift + P on Mac)`, type in `ChatGPT: Choose Predefined Prompt➕`, a selection window will pop up for users to choose their custom prompts they have added.
