### ISSUE TITLE
No available API key

### ISSUE THREAD

**Issue by camiloabrilth1999** [zhangrenyang/chatgpt#41]
I have the same problems described in this [issue](https://github.com/zhangrenyang/chatgpt/issues/15), I got several errors and it says that it has to do with the API KEY but I already tried with a direct curl of the api key and it works correctly, I think it is a problem of the extension.

![image](https://github.com/zhangrenyang/chatgpt/assets/22029023/fffeda3a-f444-4852-9ef7-a868862887ad)
![image](https://github.com/zhangrenyang/chatgpt/assets/22029023/34ca41fa-5ef4-4dcc-ac98-5a926ea92c25)

**Comment by zhangrenyang** [comment]
Please try again.
