### ISSUE TITLE
http proxy

### ISSUE THREAD

**Issue by ryanwyler** [zhangrenyang/chatgpt#44]
The extension is not using the http proxy setting I have setup within vscode.  I'm not trying to use an API proxy, I have an internal http proxy that I need to use when using vscode specifically.

**Comment by rarahim75** [comment]
I'm having the same issue.. using VsCode behind proxy.. did you manage to resolve this?

**Comment by zhangrenyang** [comment]
I have resolved this issue. Please download the [new version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) and try again.
