### ISSUE TITLE
Chat sidebar shows incorrect model in use

### ISSUE THREAD

**Issue by Shadoxity** [zhangrenyang/chatgpt#50]
Hey, I have set my model as gpt-4o-mini.
However in the side bar of the chat window it shows as 3.5-turbo.

But checking in my account I can confirm it is using 4o-mini.

Just letting you know so it can be fixed up

**Comment by zhangrenyang** [comment]
I have resolved this issue. Please update to the latest [version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) and try again.
