### ISSUE TITLE
Feature request: `chatgpt.sidebar.focus` should set focus to text input

### ISSUE THREAD

**Issue by pveierland** [zhangrenyang/chatgpt#51]
Thank you for a nice extension!

It would be good if the `chatgpt.sidebar.focus` action both makes the sidebar visible AND selects the chat box in the sidebar. This way it is easier to switch between the chat and coding while only using the keyboard.

**Comment by zhangrenyang** [comment]
I have already implemented this feature. Please download the [latest version](https://marketplace.visualstudio.com/items?itemName=zhang-renyang.chat-gpt) to try it out. If you encounter any issues, please feel free to provide feedback again. Thank you.
